#!/bin/bash

# Report WER for reports and conversational 
# Copyright 2014 QCRI (author: Ahmed Ali)
# Apache 2.0

if [ $# -ne 1 ]; then
   echo "Arguments should be the gale folder, see ../run.sh for example."
   exit 1;
fi

[ -f ./path.sh ] && . ./path.sh


galeFolder=$(readlink -f $1)
symtab=exp/tri3b/graph_bigLM/words.txt

min_lmwt=9
max_lmwt=20
for dir in exp/nnet2_online/nnet_a_gpu_online/decode_test_bigLM/; do
 for type in noNumbers; do
 #echo "Processing: $dir $type"
  rm -fr $dir/scoring_$type
  cp -pr $dir/scoring  $dir/scoring_$type
  ( cd $dir/scoring_$type;
    for x in *.tra test_filt.txt; do
	  sort -u $x > tmp$$
      join tmp$$ $galeFolder/${type}.test > $x
      rm -fr tmp$$
    done
   )

utils/run.pl LMWT=$min_lmwt:$max_lmwt $dir/scoring_$type/log/score.LMWT.log \
   cat $dir/scoring_${type}/LMWT.tra \| \
    utils/int2sym.pl -f 2- $symtab \| sed 's:\<UNK\>::g' \| \
    compute-wer --text --mode=present \
     ark:$dir/scoring_${type}/test_filt.txt  ark,p:- ">&" $dir/wer_${type}_LMWT
done
done


time=$(date +"%Y-%m-%d-%H-%M-%S")
echo "RESULTS generated by $USER at $time"


for x in exp/nnet2_online/nnet_a_gpu_online/decode_test_bigLM/ ; do [ -d $x ] && grep WER $x/wer_noNumbers_* | utils/best_wer.sh; done | sort -n -k2 




